name: infi_wheel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-98.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # google_maps_flutter: ^2.5.0
  go_router: ^12.1.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  http: ^1.1.0
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  intl: ^0.18.1
  retrofit: ^4.0.3
  flutter_hooks: ^0.20.3
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  flutter_svg: ^2.0.9
  permission_handler: ^11.0.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.2
  firebase_storage: ^11.5.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  retrofit_generator: ^8.0.3
  build_runner: ^2.4.6

  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/applogo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/applogo_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/evericons/
    - assets/icons/socials/

  fonts:
    - family: Lato
      fonts:
        - asset: "assets/fonts/Lato_Regular.ttf"
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700