name: infi_wheel
description: "P2P Car-Sharing app!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-98.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #injections
  get_it: ^7.6.7

  #webservices
  http: ^1.2.0
  json_annotation: ^4.8.1

  #routing
  go_router: ^12.1.1

  #bloc
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  #permissions
  permission_handler: ^11.0.1

  #UI
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  lottie: ^3.0.0

  #maps
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/applogo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/applogo_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/evericons/
    - assets/icons/socials/
    - assets/animations/

  fonts:
    - family: Lato
      fonts:
        - asset: "assets/fonts/Lato_Regular.ttf"
    - family: Otterco
      fonts:
        - asset: "assets/fonts/OttercoDisplay-SemiBold.otf"
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700