name: infi_wheel
description: "P2P Car-Sharing app!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <=3.4.3'

dependencies:
  flutter:
    sdk: flutter

  #injections
  get_it: ^7.7.0

  #webservices
  http: ^1.2.1
  json_annotation: ^4.8.1
  flutter_secure_storage: ^9.2.2
  dio: ^5.4.3+1

  #routing
  go_router: ^14.2.0

  #bloc
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  #permissions
  permission_handler: ^11.3.1

  #UI
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.6
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  image_picker: ^1.1.2

  #maps
  google_maps_flutter: ^2.7.0

  #local
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/applogo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/applogo_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/evericons/
    - assets/icons/socials/
    - assets/animations/

  fonts:
    - family: Lato
      fonts:
        - asset: "assets/fonts/Lato_Regular.ttf"
    - family: Otterco
      fonts:
        - asset: "assets/fonts/OttercoDisplay-SemiBold.otf"
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700